/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se.backede.jeconomix.forms.category;

import java.util.Optional;
import se.backede.jeconomix.constants.CategoryTypeEnum;
import se.backede.jeconomix.database.CategoryHandler;
import se.backede.jeconomix.dto.CategoryDto;
import se.backede.jeconomix.dto.CategoryTypeDto;
import se.backede.jeconomix.forms.basic.NegodPanel;
import se.backede.jeconomix.models.combobox.CategoryTypeComboBoxModel;
import se.backede.jeconomix.models.table.CategoryModel;
import se.backede.jeconomix.renderer.combobox.CategoryTypeComboBoxRenderer;

/**
 *
 * @author Joakim Backede ( joakim.backede@outlook.com )
 */
public class CategoryEdit extends NegodPanel {

    /**
     * Creates new form CategoryEdit
     */
    private CategoryTypeEnum TYPE = CategoryTypeEnum.TRANSFER;

    public CategoryEdit() {
        initComponents();
    }

    public CategoryEdit(CategoryTypeEnum type) {
        this.TYPE = type;
        initComponents();
        setExpenseCategoryTableData(TYPE);
        setBillCategoryTypeComboBox();
    }

    public void setExpenseCategoryTableData(CategoryTypeEnum type) {
        categoryTable.setModel(new CategoryModel(TYPE));
    }

    public void setBillCategoryTypeComboBox() {
        categoryTypeCB.setModel(new CategoryTypeComboBoxModel());
        categoryTypeCB.setRenderer(new CategoryTypeComboBoxRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        categoryTable = new javax.swing.JTable();
        categoryTypeCB = new javax.swing.JComboBox<>();
        expenseCategoryEdit = new javax.swing.JButton();
        expenseCategoryRemove = new javax.swing.JButton();
        expenseCategoryAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        categoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(categoryTable);

        categoryTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoryTypeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryTypeCBActionPerformed(evt);
            }
        });

        expenseCategoryEdit.setText("Edit");
        expenseCategoryEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenseCategoryEditActionPerformed(evt);
            }
        });

        expenseCategoryRemove.setText("Remove");

        expenseCategoryAdd.setText("Add");
        expenseCategoryAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenseCategoryAddActionPerformed(evt);
            }
        });

        jLabel1.setText("Change type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(categoryTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expenseCategoryEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expenseCategoryRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expenseCategoryAdd)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expenseCategoryAdd)
                    .addComponent(expenseCategoryRemove)
                    .addComponent(expenseCategoryEdit)
                    .addComponent(categoryTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void categoryTypeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryTypeCBActionPerformed
        int selectedRow = categoryTable.getSelectedRow();
        CategoryModel model = (CategoryModel) categoryTable.getModel();
        CategoryDto expCategory = model.getCategoryAt(selectedRow);

        CategoryTypeComboBoxModel expModel = (CategoryTypeComboBoxModel) categoryTypeCB.getModel();
        CategoryTypeDto categoryType = (CategoryTypeDto) expModel.getSelectedItem();

        CategoryHandler.getInstance().setCategoryType(expCategory, categoryType).ifPresent(category -> {
            expCategory.setCategoryType(categoryType);
            model.fireTableDataChanged();
        });
    }//GEN-LAST:event_categoryTypeCBActionPerformed

    private void expenseCategoryEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenseCategoryEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expenseCategoryEditActionPerformed

    private void expenseCategoryAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenseCategoryAddActionPerformed
        new AddCategory(null, false).setVisible(true);
    }//GEN-LAST:event_expenseCategoryAddActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable categoryTable;
    private javax.swing.JComboBox<String> categoryTypeCB;
    private javax.swing.JButton expenseCategoryAdd;
    private javax.swing.JButton expenseCategoryEdit;
    private javax.swing.JButton expenseCategoryRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void init() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
