/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se.backede.jeconomix.forms;

import java.util.List;
import java.util.Optional;
import se.backede.jeconomix.database.BillCategoryHandler;
import se.backede.jeconomix.database.CategoryTypeHandler;
import se.backede.jeconomix.database.ExpenseCategoryHandler;
import se.backede.jeconomix.dto.BillCategoryDto;
import se.backede.jeconomix.dto.CategoryTypeDto;
import se.backede.jeconomix.dto.ExpenseCategoryDto;
import se.backede.jeconomix.models.combobox.CategoryTypeComboBoxModel;
import se.backede.jeconomix.models.table.BillCategoryModel;
import se.backede.jeconomix.models.table.ExpenseCategoryModel;
import se.backede.jeconomix.renderer.combobox.CategoryTypeComboBoxRenderer;

/**
 *
 * @author Joakim Backede ( joakim.backede@outlook.com )
 */
public class CategoryHandler extends javax.swing.JDialog {

    /**
     * Creates new form CategoryHandler
     */
    public CategoryHandler(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBillCategoryTableData();
        setExpenseCategoryTableData();
        setExpenseCategoryTypeComboBox();
        setBillCategoryTypeComboBox();
    }
    
    public void setBillCategoryTableData() {
        Optional<List<BillCategoryDto>> allBillCategories = BillCategoryHandler.getInstance().getAllBillCategories();
        if (allBillCategories.isPresent()) {
            BillCategoryModel model = new BillCategoryModel(allBillCategories.get());
            billCategoryTable.setModel(model);
        }
    }
    
    public void setExpenseCategoryTableData() {
        Optional<List<ExpenseCategoryDto>> allExpenseCategories = ExpenseCategoryHandler.getInstance().getAllExpenseCategories();
        if (allExpenseCategories.isPresent()) {
            ExpenseCategoryModel model = new ExpenseCategoryModel(allExpenseCategories.get());
            expenseCategoryTable.setModel(model);
        }
    }
    
    public void setExpenseCategoryTypeComboBox() {
        Optional<List<CategoryTypeDto>> allCategoryTypes = CategoryTypeHandler.getInstance().getAllCategoryTypes();
        if (allCategoryTypes.isPresent()) {
            CategoryTypeComboBoxModel model = new CategoryTypeComboBoxModel(allCategoryTypes.get());
            expenseCategoryTypeCB.setModel(model);
            expenseCategoryTypeCB.setRenderer(new CategoryTypeComboBoxRenderer());
        }
    }
    
    public void setBillCategoryTypeComboBox() {
        Optional<List<CategoryTypeDto>> allCategoryTypes = CategoryTypeHandler.getInstance().getAllCategoryTypes();
        if (allCategoryTypes.isPresent()) {
            CategoryTypeComboBoxModel model = new CategoryTypeComboBoxModel(allCategoryTypes.get());
            billCategoryTypeCB.setModel(model);
            billCategoryTypeCB.setRenderer(new CategoryTypeComboBoxRenderer());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        expenseCategoryTab = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        expenseCategoryTable = new javax.swing.JTable();
        expenseCategoryAdd = new javax.swing.JButton();
        expenseCategoryRemove = new javax.swing.JButton();
        expenseCategoryEdit = new javax.swing.JButton();
        expenseCategoryTypeCB = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        billCategoryTable = new javax.swing.JTable();
        billCategoryAddButton = new javax.swing.JButton();
        billCategoryRemoveButton = new javax.swing.JButton();
        billCategoryTypeCB = new javax.swing.JComboBox<>();
        jButton5billCategoryEditButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        expenseCategoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(expenseCategoryTable);

        expenseCategoryAdd.setText("Add");

        expenseCategoryRemove.setText("Remove");

        expenseCategoryEdit.setText("Edit");
        expenseCategoryEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenseCategoryEditActionPerformed(evt);
            }
        });

        expenseCategoryTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(expenseCategoryTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expenseCategoryEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expenseCategoryRemove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expenseCategoryAdd)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expenseCategoryAdd)
                    .addComponent(expenseCategoryRemove)
                    .addComponent(expenseCategoryEdit)
                    .addComponent(expenseCategoryTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        expenseCategoryTab.addTab("Expense category", jPanel2);

        billCategoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(billCategoryTable);

        billCategoryAddButton.setText("Add");
        billCategoryAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billCategoryAddButtonActionPerformed(evt);
            }
        });

        billCategoryRemoveButton.setText("Remove");

        billCategoryTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton5billCategoryEditButton.setText("Edit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(billCategoryTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5billCategoryEditButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(billCategoryRemoveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(billCategoryAddButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billCategoryAddButton)
                    .addComponent(billCategoryRemoveButton)
                    .addComponent(billCategoryTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5billCategoryEditButton))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        expenseCategoryTab.addTab("Bill category", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(expenseCategoryTab, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(expenseCategoryTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        expenseCategoryTab.getAccessibleContext().setAccessibleName("Bill categories");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void expenseCategoryEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenseCategoryEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expenseCategoryEditActionPerformed

    private void billCategoryAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billCategoryAddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billCategoryAddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoryHandler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoryHandler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoryHandler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoryHandler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CategoryHandler dialog = new CategoryHandler(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton billCategoryAddButton;
    private javax.swing.JButton billCategoryRemoveButton;
    private javax.swing.JTable billCategoryTable;
    private javax.swing.JComboBox<String> billCategoryTypeCB;
    private javax.swing.JButton expenseCategoryAdd;
    private javax.swing.JButton expenseCategoryEdit;
    private javax.swing.JButton expenseCategoryRemove;
    private javax.swing.JTabbedPane expenseCategoryTab;
    private javax.swing.JTable expenseCategoryTable;
    private javax.swing.JComboBox<String> expenseCategoryTypeCB;
    private javax.swing.JButton jButton5billCategoryEditButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
