/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se.backede.jeconomix.forms;

import java.time.YearMonth;
import javax.swing.Box;
import javax.swing.JPanel;
import lombok.extern.slf4j.Slf4j;
import org.jfree.data.time.Month;
import se.backede.jeconomix.forms.basic.component.MonthWidget;

/**
 *
 * @author Joakim Backede ( joakim.backede@outlook.com )
 */
@Slf4j
public class MonthOverview extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    YearMonth CURRENT = YearMonth.of(2018, Month.MARCH);
    YearMonth CURRENT2 = YearMonth.of(2019, Month.MARCH);
    YearMonth CURRENT3 = YearMonth.of(2020, Month.MARCH);

    /**
     * Creates new form Test
     */
    public MonthOverview() {
        initComponents();

        //Panel1
        JPanel view = ((JPanel) month1ScrollPane.getViewport().getView());
        Box verticalBox1 = Box.createVerticalBox();
        verticalBox1.add(Box.createGlue());

        verticalBox1.add(new MonthWidget(CURRENT));
        verticalBox1.add(new MonthWidget(CURRENT2));
        verticalBox1.add(new MonthWidget(CURRENT3));

        view.add(verticalBox1);

        //Panel2
        JPanel view2 = ((JPanel) month2ScrollPane.getViewport().getView());
        Box verticalBox2 = Box.createVerticalBox();
        verticalBox2.add(Box.createGlue());

        verticalBox2.add(new MonthWidget(CURRENT));
        verticalBox2.add(new MonthWidget(CURRENT2));
        verticalBox2.add(new MonthWidget(CURRENT3));

        view2.add(verticalBox2);

        //Panel3
        JPanel view3 = ((JPanel) month3ScrollPane.getViewport().getView());
        Box verticalBox3 = Box.createVerticalBox();
        verticalBox3.add(Box.createGlue());

        verticalBox3.add(new MonthWidget(CURRENT));
        verticalBox3.add(new MonthWidget(CURRENT2));
        verticalBox3.add(new MonthWidget(CURRENT3));

        view3.add(verticalBox3);

        this.validate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        summaryPanel = new javax.swing.JPanel();
        month1ScrollPane = new javax.swing.JScrollPane();
        month1Panel = new javax.swing.JPanel();
        month2ScrollPane = new javax.swing.JScrollPane();
        month2Panel = new javax.swing.JPanel();
        month3ScrollPane = new javax.swing.JScrollPane();
        month3Panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));

        summaryPanel.setPreferredSize(new java.awt.Dimension(1200, 300));
        summaryPanel.setLayout(new java.awt.GridLayout(1, 3));

        month1ScrollPane.setBorder(null);
        month1ScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        month1ScrollPane.setPreferredSize(new java.awt.Dimension(425, 75));
        month1ScrollPane.setViewportView(month1Panel);

        month1Panel.setBackground(new java.awt.Color(255, 255, 255));
        month1ScrollPane.setViewportView(month1Panel);

        summaryPanel.add(month1ScrollPane);

        month2ScrollPane.setBorder(null);
        month2ScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        month2ScrollPane.setPreferredSize(new java.awt.Dimension(425, 75));
        month2ScrollPane.setViewportView(month2Panel);

        month2Panel.setBackground(new java.awt.Color(255, 255, 255));
        month2ScrollPane.setViewportView(month2Panel);

        summaryPanel.add(month2ScrollPane);

        month3ScrollPane.setBorder(null);
        month3ScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        month3ScrollPane.setAutoscrolls(true);
        month3ScrollPane.setPreferredSize(new java.awt.Dimension(425, 75));
        month3ScrollPane.setViewportView(month3Panel);

        month3Panel.setBackground(new java.awt.Color(255, 255, 255));
        month3ScrollPane.setViewportView(month3Panel);

        summaryPanel.add(month3ScrollPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(summaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(summaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel month1Panel;
    private javax.swing.JScrollPane month1ScrollPane;
    private javax.swing.JPanel month2Panel;
    private javax.swing.JScrollPane month2ScrollPane;
    private javax.swing.JPanel month3Panel;
    private javax.swing.JScrollPane month3ScrollPane;
    private javax.swing.JPanel summaryPanel;
    // End of variables declaration//GEN-END:variables
}
