/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se.backede.jeconomix.forms;

import java.time.Month;
import java.time.Year;
import java.util.HashMap;
import javax.swing.Box;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import lombok.extern.slf4j.Slf4j;
import se.backede.jeconomix.constants.BudgetQuarterEnum;
import se.backede.jeconomix.constants.CategoryTypeEnum;
import se.backede.jeconomix.event.events.dto.BudgetEventDto;
import se.backede.jeconomix.forms.basic.component.MonthWidget;

/**
 *
 * @author Joakim Backede ( joakim.backede@outlook.com )
 */
@Slf4j
public class MonthOverview extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    public MonthOverview() {
        initComponents();
    }

    public void init(BudgetQuarterEnum quarter, Year year, CategoryTypeEnum... categories) {

        addBox(month1ScrollPane, quarter, quarter.firstMonth(), year, categories);
        addBox(month2ScrollPane, quarter, quarter.secondMonth(), year, categories);
        addBox(month3ScrollPane, quarter, quarter.thirdMonth(), year, categories);
    }

    private void addBox(JScrollPane pane, BudgetQuarterEnum quarter, Month month, Year year, CategoryTypeEnum... categories) {
        JPanel view = ((JPanel) pane.getViewport().getView());
        Box verticalBox1 = Box.createVerticalBox();
        verticalBox1.add(Box.createGlue());

        for (CategoryTypeEnum category : categories) {
            BudgetEventDto dto = BudgetEventDto.builder()
                    .month(month)
                    .year(year)
                    .quarter(quarter)
                    .category(category)
                    .build();
            verticalBox1.add(new MonthWidget(dto));
        }

        view.add(verticalBox1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        summaryPanel = new javax.swing.JPanel();
        month1ScrollPane = new javax.swing.JScrollPane();
        month1Panel = new javax.swing.JPanel();
        month2ScrollPane = new javax.swing.JScrollPane();
        month2Panel = new javax.swing.JPanel();
        month3ScrollPane = new javax.swing.JScrollPane();
        month3Panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));

        summaryPanel.setPreferredSize(new java.awt.Dimension(1200, 300));
        summaryPanel.setLayout(new java.awt.GridLayout(1, 3));

        month1ScrollPane.setBorder(null);
        month1ScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        month1ScrollPane.setPreferredSize(new java.awt.Dimension(425, 75));
        month1ScrollPane.setViewportView(month1Panel);

        month1Panel.setBackground(new java.awt.Color(255, 255, 255));
        month1ScrollPane.setViewportView(month1Panel);

        summaryPanel.add(month1ScrollPane);

        month2ScrollPane.setBorder(null);
        month2ScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        month2ScrollPane.setPreferredSize(new java.awt.Dimension(425, 75));
        month2ScrollPane.setViewportView(month2Panel);

        month2Panel.setBackground(new java.awt.Color(255, 255, 255));
        month2ScrollPane.setViewportView(month2Panel);

        summaryPanel.add(month2ScrollPane);

        month3ScrollPane.setBorder(null);
        month3ScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        month3ScrollPane.setAutoscrolls(true);
        month3ScrollPane.setPreferredSize(new java.awt.Dimension(425, 75));
        month3ScrollPane.setViewportView(month3Panel);

        month3Panel.setBackground(new java.awt.Color(255, 255, 255));
        month3ScrollPane.setViewportView(month3Panel);

        summaryPanel.add(month3ScrollPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(summaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(summaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel month1Panel;
    private javax.swing.JScrollPane month1ScrollPane;
    private javax.swing.JPanel month2Panel;
    private javax.swing.JScrollPane month2ScrollPane;
    private javax.swing.JPanel month3Panel;
    private javax.swing.JScrollPane month3ScrollPane;
    private javax.swing.JPanel summaryPanel;
    // End of variables declaration//GEN-END:variables
}
