/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se.backede.jeconomix.forms.budget;

import java.time.YearMonth;
import java.util.List;
import java.util.function.Consumer;
import javax.swing.JLabel;
import javax.swing.JTable;
import se.backede.jeconomix.constants.CategoryTypeEnum;
import se.backede.jeconomix.dto.budget.BudgetExpenseDto;
import se.backede.jeconomix.event.EventController;
import se.backede.jeconomix.event.events.BudgetEvent;
import se.backede.jeconomix.forms.basic.NegodPanel;
import se.backede.jeconomix.models.table.BudgetModel;

/**
 *
 * @author Joakim Backede ( joakim.backede@outlook.com )
 */
public class BudgetTable extends NegodPanel {

    private YearMonth BUDGET_MONTH = YearMonth.now();
    private CategoryTypeEnum CATEGORY = CategoryTypeEnum.INCOME;

    /**
     * Creates new form BudgetTable
     */
    public BudgetTable() {
        initComponents();
    }

    public BudgetTable(YearMonth currentYearMonth, CategoryTypeEnum category) {
        this.BUDGET_MONTH = currentYearMonth;
        this.CATEGORY = category;
        initComponents();
    }

    private void setUpTable(JTable table, YearMonth budgetMonth, JLabel lbl, CategoryTypeEnum category) {
        budgetTable.setModel(new BudgetModel(budgetMonth, category));
        //setUpDropDownColumn(table, table.getColumnModel().getColumn(0), category);
        BudgetModel billModel = (BudgetModel) table.getModel();
    }

    public void setEvents() {

        Consumer<BudgetExpenseDto> createBudgetExpense = (dto) -> {
            if (dto.getBudget().getMonth().equals(BUDGET_MONTH.getMonth()) && dto.getBudget().getYear() == BUDGET_MONTH.getYear()) {
                if (dto.getCategory().getCategoryType().getType().equals(CATEGORY)) {
                    BudgetModel icomeModel = (BudgetModel) budgetTable.getModel();
                    icomeModel.addBudgetExpence(dto);
                }
            }
        };
        EventController.getInstance().addObserver(BudgetEvent.ADD_BUDGET_ROW, createBudgetExpense);

        Consumer<List<BudgetExpenseDto>> addBudgetRow = (dto) -> {
            for (BudgetExpenseDto budgetExpenseDto : dto) {
                if (budgetExpenseDto.getBudget().getMonth().equals(BUDGET_MONTH.getMonth()) && budgetExpenseDto.getBudget().getYear() == BUDGET_MONTH.getYear()) {
                    if (budgetExpenseDto.getCategory().getCategoryType().getType().equals(CATEGORY)) {
                        BudgetModel model = (BudgetModel) budgetTable.getModel();
                        model.addBudgetExpence(budgetExpenseDto);
                    }
                }
            }
        };
        EventController.getInstance().addObserver(BudgetEvent.ADD_BUDGET_LIST, addBudgetRow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        budgetTable = new javax.swing.JTable();

        budgetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        budgetTable.setFocusCycleRoot(true);
        jScrollPane1.setViewportView(budgetTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable budgetTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void init() {
    }
}
