/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se.backede.jeconomix.forms.budget;

import java.time.YearMonth;
import javax.swing.Box;
import javax.swing.JPanel;
import se.backede.jeconomix.constants.CategoryTypeEnum;
import static se.backede.jeconomix.database.entity.budget.Budget_.year;
import se.backede.jeconomix.event.events.dto.BudgetEventDto;
import se.backede.jeconomix.forms.basic.component.MonthWidget;

/**
 *
 * @author Joakim Backede ( joakim.backede@outlook.com )
 */
public class BudgetList extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form BudgetMonthDev
     */
    public BudgetList() {
        initComponents();
    }

    public void init(YearMonth yearMonth, CategoryTypeEnum... categories) {

        JPanel view = ((JPanel) scrollPane.getViewport().getView());

        view.removeAll();

        Box verticalBox1 = Box.createVerticalBox();
        verticalBox1.add(Box.createGlue());

        for (CategoryTypeEnum category : categories) {
            BudgetEventDto dto = BudgetEventDto.builder()
                    .yearMonth(yearMonth)
                    .category(category)
                    .build();
            verticalBox1.add(new MonthWidget(dto));
        }

        view.add(verticalBox1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        month1Panel = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(1, 3));

        scrollPane.setBorder(null);
        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setPreferredSize(new java.awt.Dimension(425, 75));

        month1Panel.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane.setViewportView(month1Panel);

        add(scrollPane);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel month1Panel;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
