/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se.backede.jeconomix.forms.budget;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import lombok.extern.slf4j.Slf4j;
import se.backede.jeconomix.constants.CategoryTypeEnum;
import se.backede.jeconomix.dto.budget.BudgetExpenseDto;
import se.backede.jeconomix.event.EventController;
import se.backede.jeconomix.event.events.UiEvent;
import se.backede.jeconomix.event.events.dto.BudgetEventDto;

/**
 *
 * @author Joakim Backede ( joakim.backede@outlook.com )
 */
@Slf4j
public class BudgetMonthWidget extends javax.swing.JPanel {

    /**
     * Creates new form MonthWidget
     */
    public BudgetMonthWidget() {
        initComponents();
    }

    public BudgetMonthWidget(BudgetEventDto currentBudget, List<BudgetExpenseDto> expenses, Integer currentTransactionSums) {
        initComponents();

        budgetTable1.init(currentBudget, expenses);

        budgetTable1.setVisible(false);
        this.validate();

        startUp(currentBudget, currentTransactionSums);
    }

    public void startUp(BudgetEventDto budgetEvent, Integer currentTransactionSums) {

        summaryWidget1.init(budgetEvent, currentTransactionSums, budgetTable1.getTotalSum());

        Consumer<BudgetEventDto> setVisible = (dto) -> {
            if (dto.equals(budgetEvent)) {
                budgetTable1.setVisible(true);
                this.validate();
            }
        };
        EventController.getInstance().addObserver(UiEvent.SHOW, setVisible);

        Consumer<BudgetEventDto> hide = (dto) -> {
            if (dto.equals(budgetEvent)) {
                budgetTable1.setVisible(false);
                this.validate();
            }
        };
        EventController.getInstance().addObserver(UiEvent.HIDE, hide);

    }

//
//    public void removeBudgetExpense(JTable table) {
//        BudgetModel model = (BudgetModel) table.getModel();
//        model.removeBudgetExpenseAt(table.getSelectedRow());
//    }
//
//    private void addBudgetLine(CategoryTypeEnum category) {
//        AddBudgetLine budgetLine = new AddBudgetLine(CURRENT_YEAR_MONTH);
//        budgetLine.startUp(category);
//        budgetLine.setVisible(true);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        summaryWidget1 = new se.backede.jeconomix.forms.budget.BudgetSummaryWidget();
        budgetTable1 = new se.backede.jeconomix.forms.budget.BudgetTable();

        setLayout(new java.awt.GridBagLayout());

        summaryWidget1.setPreferredSize(new java.awt.Dimension(400, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(summaryWidget1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(budgetTable1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private se.backede.jeconomix.forms.budget.BudgetTable budgetTable1;
    private se.backede.jeconomix.forms.budget.BudgetSummaryWidget summaryWidget1;
    // End of variables declaration//GEN-END:variables
}
