/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se.backede.jeconomix.forms.budget;

import java.awt.Color;
import java.math.BigDecimal;
import java.util.function.Consumer;
import org.apache.commons.lang3.StringUtils;
import static se.backede.jeconomix.constants.CategoryTypeEnum.BILL;
import static se.backede.jeconomix.constants.CategoryTypeEnum.CREDIT_CARD;
import static se.backede.jeconomix.constants.CategoryTypeEnum.EXPENSE;
import static se.backede.jeconomix.constants.CategoryTypeEnum.INCOME;
import static se.backede.jeconomix.constants.CategoryTypeEnum.LOAN;
import static se.backede.jeconomix.constants.CategoryTypeEnum.POCKET_MONEY;
import static se.backede.jeconomix.constants.CategoryTypeEnum.SAVING;
import static se.backede.jeconomix.constants.CategoryTypeEnum.TRANSFER;
import se.backede.jeconomix.event.EventController;
import se.backede.jeconomix.event.events.BudgetEvent;
import se.backede.jeconomix.event.events.UiEvent;
import se.backede.jeconomix.event.events.dto.BudgetEventDto;
import se.backede.jeconomix.event.events.dto.BudgetExpenseEventDto;

/**
 *
 * @author Joakim Backede ( joakim.backede@outlook.com )
 */
public class BudgetSummaryWidget extends javax.swing.JPanel {

    boolean tableHidden = true;
    BudgetEventDto CURRENT_BUDGET;

    /**
     * Creates new form SummaryWidget
     */
    public BudgetSummaryWidget() {
        initComponents();
    }

    public void setEvents() {
        Consumer<BudgetExpenseEventDto> addToTotal = (dto) -> {
            if (dto.getBudgetEvent().equals(CURRENT_BUDGET)) {
                addToSum(dto.getBudgetExpense().getEstimatedsum());
            }
        };
        EventController.getInstance().addObserver(BudgetEvent.ADD_BUDGET_ROW, addToTotal);

        Consumer<BudgetExpenseEventDto> removeFromTotal = (dto) -> {
            if (dto.getBudgetEvent().equals(CURRENT_BUDGET)) {
                subtractFromSum(dto.getBudgetExpense().getEstimatedsum());
            }
        };
        EventController.getInstance().addObserver(BudgetEvent.DELETE_BUDGET_ROW, removeFromTotal);
    }

    public void addToSum(BigDecimal value) {
        budgetProgressBar.setMaximum(budgetProgressBar.getMaximum() + value.intValueExact());
        sumLabel.setText(String.valueOf(budgetProgressBar.getMaximum()).concat(" Kr"));
    }

    public void subtractFromSum(BigDecimal value) {
        budgetProgressBar.setMaximum(budgetProgressBar.getMaximum() - value.intValueExact());
        sumLabel.setText(String.valueOf(budgetProgressBar.getMaximum()).concat(" Kr"));
    }

    public void init(BudgetEventDto dto, Integer sum, BigDecimal budget) {

        CURRENT_BUDGET = dto;

        budgetProgressBar.setMaximum(budget.intValueExact());

        if (sum != null) {
            budgetProgressBar.setValue(sum);
            budgetProgressBar.setString(String.valueOf(sum).concat(" Kr"));
        } else {
            budgetProgressBar.setString("0 Kr");
        }

        titleLabel.setText(StringUtils.capitalize(dto.getCategory().name().toLowerCase()));
        sumLabel.setText(budget.toPlainString().concat(" Kr"));

        switch (dto.getCategory()) {
            case INCOME:
            case SAVING:
                titlePanel.setBackground(Color.GREEN);
                sumLabel.setBackground(Color.GREEN);
                break;
            case EXPENSE:
            case BILL:
            case CREDIT_CARD:
            case LOAN:
                titlePanel.setBackground(Color.RED);
                sumLabel.setBackground(Color.RED);
                break;
            case TRANSFER:
            case POCKET_MONEY:
                titlePanel.setBackground(Color.YELLOW);
                sumLabel.setBackground(Color.YELLOW);
                break;
            default:
                throw new AssertionError();
        }

        setEvents();

    }

    public void showOrHide() {
        EventController.getInstance().notifyObservers(tableHidden ? UiEvent.SHOW : UiEvent.HIDE, () -> CURRENT_BUDGET);
        tableHidden = !tableHidden;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        sumPanel = new javax.swing.JPanel();
        sumLabel = new javax.swing.JLabel();
        progressPanel = new javax.swing.JPanel();
        budgetProgressBar = new javax.swing.JProgressBar();

        setMinimumSize(new java.awt.Dimension(400, 25));
        setPreferredSize(new java.awt.Dimension(500, 25));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {2};
        layout.rowHeights = new int[] {1};
        layout.columnWeights = new double[] {1.0};
        layout.rowWeights = new double[] {3.0};
        setLayout(layout);

        titlePanel.setPreferredSize(new java.awt.Dimension(150, 25));
        titlePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titlePanelMouseClicked(evt);
            }
        });
        titlePanel.setLayout(new java.awt.GridBagLayout());

        titleLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleLabel.setText("Transaction type");
        titleLabel.setPreferredSize(new java.awt.Dimension(150, 25));
        titleLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titleLabelMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        titlePanel.add(titleLabel, gridBagConstraints);

        add(titlePanel, new java.awt.GridBagConstraints());

        sumPanel.setBackground(new java.awt.Color(255, 255, 255));
        sumPanel.setPreferredSize(new java.awt.Dimension(100, 25));
        sumPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumPanelMouseClicked(evt);
            }
        });
        sumPanel.setLayout(new java.awt.GridBagLayout());

        sumLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        sumLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sumLabel.setText("Budget sum");
        sumLabel.setAlignmentY(0.0F);
        sumLabel.setPreferredSize(new java.awt.Dimension(100, 25));
        sumLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumLabelMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 1;
        sumPanel.add(sumLabel, gridBagConstraints);

        add(sumPanel, new java.awt.GridBagConstraints());

        progressPanel.setBackground(new java.awt.Color(255, 255, 255));
        progressPanel.setMinimumSize(new java.awt.Dimension(150, 25));
        progressPanel.setPreferredSize(new java.awt.Dimension(150, 25));
        progressPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BudgetSummaryWidget.this.mouseClicked(evt);
            }
        });
        progressPanel.setLayout(new java.awt.GridBagLayout());

        budgetProgressBar.setBorderPainted(false);
        budgetProgressBar.setMaximumSize(new java.awt.Dimension(32767, 32767));
        budgetProgressBar.setMinimumSize(new java.awt.Dimension(0, 0));
        budgetProgressBar.setPreferredSize(new java.awt.Dimension(150, 25));
        budgetProgressBar.setString("0 Kr");
        budgetProgressBar.setStringPainted(true);
        budgetProgressBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                budgetProgressBarMouseClicked(evt);
            }
        });
        progressPanel.add(budgetProgressBar, new java.awt.GridBagConstraints());

        add(progressPanel, new java.awt.GridBagConstraints());
        progressPanel.getAccessibleContext().setAccessibleDescription("");
        progressPanel.getAccessibleContext().setAccessibleParent(progressPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void titlePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlePanelMouseClicked
        showOrHide();
    }//GEN-LAST:event_titlePanelMouseClicked

    private void titleLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleLabelMouseClicked
        showOrHide();
    }//GEN-LAST:event_titleLabelMouseClicked

    private void sumLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumLabelMouseClicked
        showOrHide();
    }//GEN-LAST:event_sumLabelMouseClicked

    private void sumPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumPanelMouseClicked
        showOrHide();
    }//GEN-LAST:event_sumPanelMouseClicked

    private void budgetProgressBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_budgetProgressBarMouseClicked
        showOrHide();
    }//GEN-LAST:event_budgetProgressBarMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        showOrHide();
    }//GEN-LAST:event_formMouseClicked

    private void mouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClicked
        showOrHide();
    }//GEN-LAST:event_mouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar budgetProgressBar;
    private javax.swing.JPanel progressPanel;
    private javax.swing.JLabel sumLabel;
    private javax.swing.JPanel sumPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
