/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se.backede.jeconomix.forms.budget;

import java.math.BigDecimal;
import java.util.List;
import java.util.function.Consumer;
import se.backede.jeconomix.constants.CategoryTypeEnum;
import se.backede.jeconomix.dto.budget.BudgetExpenseDto;
import se.backede.jeconomix.event.EventController;
import se.backede.jeconomix.event.events.BudgetEvent;
import se.backede.jeconomix.utils.BudgetUtils;

/**
 *
 * @author Joakim Backede ( joakim.backede@outlook.com )
 */
public class BudgetTotal extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form BudgetTotal
     */
    public BudgetTotal() {
        initComponents();
        setEvents();
    }

    private void setEvents() {
        Consumer<List<BudgetExpenseDto>> setTotalValue = (dtoList) -> {

            BigDecimal billSum = BudgetUtils.getSumsFromBudgetExpense(dtoList, CategoryTypeEnum.BILL);
            billSumLbl.setText("".concat(billSum.toString()));

            BigDecimal expenseSum = BudgetUtils.getSumsFromBudgetExpense(dtoList, CategoryTypeEnum.EXPENSE);
            expenseSumLbl.setText("".concat(expenseSum.toString()));

            BigDecimal incomeSum = BudgetUtils.getSumsFromBudgetExpense(dtoList, CategoryTypeEnum.INCOME);
            incomeSumLbl.setText(" ".concat(incomeSum.toString()));

            BigDecimal add = incomeSum.add(billSum.add(expenseSum));
            totalSumLbl.setText(add.toString());
        };

        EventController.getInstance().addObserver(BudgetEvent.SET_BUDGET_TOTAL, setTotalValue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        expenseLbl = new javax.swing.JLabel();
        billLbl = new javax.swing.JLabel();
        incomeLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        totalLbl = new javax.swing.JLabel();
        incomeSumLbl = new javax.swing.JLabel();
        billSumLbl = new javax.swing.JLabel();
        expenseSumLbl = new javax.swing.JLabel();
        totalSumLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        expenseLbl.setBackground(new java.awt.Color(0, 0, 0));
        expenseLbl.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        expenseLbl.setForeground(new java.awt.Color(153, 0, 0));
        expenseLbl.setText("Expense");

        billLbl.setBackground(new java.awt.Color(0, 0, 0));
        billLbl.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        billLbl.setForeground(new java.awt.Color(153, 0, 0));
        billLbl.setText("Bill");

        incomeLbl.setBackground(new java.awt.Color(0, 0, 0));
        incomeLbl.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        incomeLbl.setForeground(new java.awt.Color(0, 51, 51));
        incomeLbl.setText("Income");

        totalLbl.setBackground(new java.awt.Color(0, 0, 0));
        totalLbl.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        totalLbl.setForeground(new java.awt.Color(0, 0, 0));
        totalLbl.setText("Total");

        incomeSumLbl.setBackground(new java.awt.Color(0, 0, 0));
        incomeSumLbl.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        incomeSumLbl.setForeground(new java.awt.Color(0, 51, 51));
        incomeSumLbl.setText("-");

        billSumLbl.setBackground(new java.awt.Color(0, 0, 0));
        billSumLbl.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        billSumLbl.setForeground(new java.awt.Color(153, 0, 0));
        billSumLbl.setText("-");

        expenseSumLbl.setBackground(new java.awt.Color(0, 0, 0));
        expenseSumLbl.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        expenseSumLbl.setForeground(new java.awt.Color(153, 0, 0));
        expenseSumLbl.setText("-");

        totalSumLbl.setBackground(new java.awt.Color(0, 0, 0));
        totalSumLbl.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        totalSumLbl.setForeground(new java.awt.Color(0, 0, 0));
        totalSumLbl.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(totalLbl)
                .addGap(27, 27, 27)
                .addComponent(totalSumLbl))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(incomeLbl)
                    .addComponent(billLbl)
                    .addComponent(expenseLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(expenseSumLbl)
                    .addComponent(billSumLbl)
                    .addComponent(incomeSumLbl)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(incomeLbl)
                    .addComponent(incomeSumLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billLbl)
                    .addComponent(billSumLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expenseLbl)
                    .addComponent(expenseSumLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLbl)
                    .addComponent(totalSumLbl))
                .addGap(0, 8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel billLbl;
    private javax.swing.JLabel billSumLbl;
    private javax.swing.JLabel expenseLbl;
    private javax.swing.JLabel expenseSumLbl;
    private javax.swing.JLabel incomeLbl;
    private javax.swing.JLabel incomeSumLbl;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel totalLbl;
    private javax.swing.JLabel totalSumLbl;
    // End of variables declaration//GEN-END:variables
}
